<?php
/**
 * ObjectiveSchemaTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  RusticiSoftware\Cloud\V2
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SCORM Cloud Rest API
 *
 * REST API used for SCORM Cloud integrations.
 *
 * OpenAPI spec version: 2.0 beta
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace RusticiSoftware\Cloud\V2;

/**
 * ObjectiveSchemaTest Class Doc Comment
 *
 * @category    Class */
// * @description ObjectiveSchema
/**
 * @package     RusticiSoftware\Cloud\V2
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ObjectiveSchemaTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ObjectiveSchema"
     */
    public function testObjectiveSchema()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "primary"
     */
    public function testPropertyPrimary()
    {

    }

    /**
     * Test attribute "score"
     */
    public function testPropertyScore()
    {

    }

    /**
     * Test attribute "score_max"
     */
    public function testPropertyScoreMax()
    {

    }

    /**
     * Test attribute "score_min"
     */
    public function testPropertyScoreMin()
    {

    }

    /**
     * Test attribute "score_raw"
     */
    public function testPropertyScoreRaw()
    {

    }

    /**
     * Test attribute "previous_score_scaled"
     */
    public function testPropertyPreviousScoreScaled()
    {

    }

    /**
     * Test attribute "first_score_scaled"
     */
    public function testPropertyFirstScoreScaled()
    {

    }

    /**
     * Test attribute "progress_measure"
     */
    public function testPropertyProgressMeasure()
    {

    }

    /**
     * Test attribute "first_success_time_stamp"
     */
    public function testPropertyFirstSuccessTimeStamp()
    {

    }

    /**
     * Test attribute "objective_completion"
     */
    public function testPropertyObjectiveCompletion()
    {

    }

    /**
     * Test attribute "objective_success"
     */
    public function testPropertyObjectiveSuccess()
    {

    }

    /**
     * Test attribute "previous_objective_success"
     */
    public function testPropertyPreviousObjectiveSuccess()
    {

    }

}
