<?php
/**
 * LearnerPreferenceSchema
 *
 * PHP version 5
 *
 * @category Class
 * @package  RusticiSoftware\Cloud\V2
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SCORM Cloud Rest API
 *
 * REST API used for SCORM Cloud integrations.
 *
 * OpenAPI spec version: 2.0 beta
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace RusticiSoftware\Cloud\V2\Model;

use \ArrayAccess;

/**
 * LearnerPreferenceSchema Class Doc Comment
 *
 * @category    Class */
/** 
 * @package     RusticiSoftware\Cloud\V2
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LearnerPreferenceSchema implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'LearnerPreferenceSchema';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'audio_level' => 'double',
        'language' => 'string',
        'delivery_speed' => 'double',
        'audio_captioning' => 'int'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'audio_level' => 'audioLevel',
        'language' => 'language',
        'delivery_speed' => 'deliverySpeed',
        'audio_captioning' => 'audioCaptioning'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'audio_level' => 'setAudioLevel',
        'language' => 'setLanguage',
        'delivery_speed' => 'setDeliverySpeed',
        'audio_captioning' => 'setAudioCaptioning'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'audio_level' => 'getAudioLevel',
        'language' => 'getLanguage',
        'delivery_speed' => 'getDeliverySpeed',
        'audio_captioning' => 'getAudioCaptioning'
    );

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['audio_level'] = isset($data['audio_level']) ? $data['audio_level'] : null;
        $this->container['language'] = isset($data['language']) ? $data['language'] : null;
        $this->container['delivery_speed'] = isset($data['delivery_speed']) ? $data['delivery_speed'] : null;
        $this->container['audio_captioning'] = isset($data['audio_captioning']) ? $data['audio_captioning'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        return true;
    }


    /**
     * Gets audio_level
     * @return double
     */
    public function getAudioLevel()
    {
        return $this->container['audio_level'];
    }

    /**
     * Sets audio_level
     * @param double $audio_level
     * @return $this
     */
    public function setAudioLevel($audio_level)
    {
        $this->container['audio_level'] = $audio_level;

        return $this;
    }

    /**
     * Gets language
     * @return string
     */
    public function getLanguage()
    {
        return $this->container['language'];
    }

    /**
     * Sets language
     * @param string $language
     * @return $this
     */
    public function setLanguage($language)
    {
        $this->container['language'] = $language;

        return $this;
    }

    /**
     * Gets delivery_speed
     * @return double
     */
    public function getDeliverySpeed()
    {
        return $this->container['delivery_speed'];
    }

    /**
     * Sets delivery_speed
     * @param double $delivery_speed
     * @return $this
     */
    public function setDeliverySpeed($delivery_speed)
    {
        $this->container['delivery_speed'] = $delivery_speed;

        return $this;
    }

    /**
     * Gets audio_captioning
     * @return int
     */
    public function getAudioCaptioning()
    {
        return $this->container['audio_captioning'];
    }

    /**
     * Sets audio_captioning
     * @param int $audio_captioning
     * @return $this
     */
    public function setAudioCaptioning($audio_captioning)
    {
        $this->container['audio_captioning'] = $audio_captioning;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\RusticiSoftware\Cloud\V2\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\RusticiSoftware\Cloud\V2\ObjectSerializer::sanitizeForSerialization($this));
    }
}


