<?php
/**
 * SettingMetadataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  RusticiSoftware\Cloud\V2
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SCORM Cloud Rest API
 *
 * REST API used for SCORM Cloud integrations.
 *
 * OpenAPI spec version: 2.0 beta
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace RusticiSoftware\Cloud\V2;

/**
 * SettingMetadataTest Class Doc Comment
 *
 * @category    Class */
// * @description SettingMetadata
/**
 * @package     RusticiSoftware\Cloud\V2
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SettingMetadataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "SettingMetadata"
     */
    public function testSettingMetadata()
    {

    }

    /**
     * Test attribute "default"
     */
    public function testPropertyDefault()
    {

    }

    /**
     * Test attribute "data_type"
     */
    public function testPropertyDataType()
    {

    }

    /**
     * Test attribute "setting_description"
     */
    public function testPropertySettingDescription()
    {

    }

    /**
     * Test attribute "level"
     */
    public function testPropertyLevel()
    {

    }

    /**
     * Test attribute "learning_standards"
     */
    public function testPropertyLearningStandards()
    {

    }

    /**
     * Test attribute "learning_standard_variant"
     */
    public function testPropertyLearningStandardVariant()
    {

    }

    /**
     * Test attribute "fallback"
     */
    public function testPropertyFallback()
    {

    }

    /**
     * Test attribute "valid_values"
     */
    public function testPropertyValidValues()
    {

    }

}
